const PDFDocument = require('pdfkit');
const Appointment = require('../models/Appointment');

// POST /api/appointments
// Expects `hospital` object in body (no hospitalId, no hospital table needed)
exports.createAppointment = async (req, res) => {
  try {
    const { hospital, date, time, reason, patientName, patientEmail, patientPhone } = req.body;

    if (!hospital || !hospital.name || !date || !time || !patientName) {
      return res
        .status(400)
        .json({ message: 'hospital (with name), date, time and patientName are required' });
    }

    const dateTime = new Date(`${date}T${time}`);

    const appointment = await Appointment.create({
      user: req.user._id,
      hospital: {
        name: hospital.name,
        addressLine1:
          hospital.addressLine1 ||
          hospital.address?.line1 ||
          hospital.address ||
          '',
        city: hospital.city || hospital.address?.city || '',
        state: hospital.state || hospital.address?.state || '',
        pincode: hospital.pincode || hospital.address?.pincode || '',
        lat:
          hospital.lat != null
            ? hospital.lat
            : hospital.location?.coordinates?.[1],
        lng:
          hospital.lng != null
            ? hospital.lng
            : hospital.location?.coordinates?.[0],
      },
      patientName,
      patientEmail,
      patientPhone,
      date: dateTime,
      reason,
    });

    res.status(201).json({ appointment });
  } catch (err) {
    console.error('Create appointment error:', err);
    res.status(500).json({ message: 'Failed to create appointment', error: err.message });
  }
};

// GET /api/appointments/me
exports.getMyAppointments = async (req, res) => {
  try {
    const appointments = await Appointment.find({ user: req.user._id }).sort({ date: 1 });
    res.json({ appointments });
  } catch (err) {
    res.status(500).json({ message: 'Failed to fetch appointments', error: err.message });
  }
};

// GET /api/appointments/:id
exports.getAppointmentById = async (req, res) => {
  try {
    const appointment = await Appointment.findById(req.params.id).populate('user');
    if (!appointment) return res.status(404).json({ message: 'Appointment not found' });
    if (appointment.user._id.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Not authorized to view this appointment' });
    }
    res.json({ appointment });
  } catch (err) {
    res.status(500).json({ message: 'Failed to fetch appointment', error: err.message });
  }
};

// GET /api/appointments/:id/pdf
exports.getAppointmentPdf = async (req, res) => {
  try {
    const appointment = await Appointment.findById(req.params.id).populate('user');
    if (!appointment) return res.status(404).json({ message: 'Appointment not found' });
    if (appointment.user._id.toString() !== req.user._id.toString()) {
      return res.status(403).json({ message: 'Not authorized to view this appointment' });
    }

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=appointment-${appointment._id.toString()}.pdf`,
    );

    doc.pipe(res);

    // Header
    doc
      .fontSize(20)
      .text('MediCamb - Hospital Appointment Confirmation', { align: 'center' })
      .moveDown();

    doc
      .fontSize(14)
      .text(`Appointment ID: ${appointment._id.toString()}`)
      .moveDown();

    // Patient info
    doc.fontSize(16).text('Patient Details', { underline: true }).moveDown(0.5);
    doc.fontSize(12);
    doc.text(`Name: ${appointment.patientName}`);
    if (appointment.patientEmail) doc.text(`Email: ${appointment.patientEmail}`);
    if (appointment.patientPhone) doc.text(`Phone: ${appointment.patientPhone}`);
    doc.moveDown();

    // Hospital info
    const hospital = appointment.hospital;
    doc.fontSize(16).text('Hospital Details', { underline: true }).moveDown(0.5);
    doc.fontSize(12);
    doc.text(`Name: ${hospital.name}`);
    doc.text(
      `Address: ${hospital.addressLine1 || ''}${hospital.city ? ', ' + hospital.city : ''}${
        hospital.state ? ', ' + hospital.state : ''
      }${hospital.pincode ? ' - ' + hospital.pincode : ''}`,
    );
    doc.moveDown();

    // Appointment info
    doc.fontSize(16).text('Appointment Details', { underline: true }).moveDown(0.5);
    doc.fontSize(12);
    doc.text(`Date & Time: ${appointment.date.toLocaleString()}`);
    doc.text(`Status: ${appointment.status}`);
    if (appointment.reason) doc.text(`Reason: ${appointment.reason}`);
    doc.moveDown();

    doc
      .fontSize(10)
      .fillColor('gray')
      .text(
        'Note: This appointment confirmation is generated by MediCamb for your reference. Please arrive 10-15 minutes early and bring any relevant medical records.',
        { align: 'left' },
      );

    doc.end();
  } catch (err) {
    console.error('Generate appointment PDF error:', err);
    res.status(500).json({ message: 'Failed to generate PDF', error: err.message });
  }
};


